services:
#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    cba.service.user:
        class: AppBundle\Services\UserService
        arguments:
            - "@doctrine.orm.entity_manager"

    cba.service.ressource:
        class: AppBundle\Services\RessourceService
        arguments:
            - "@doctrine.orm.entity_manager"